# Generated by Django 3.2.7 on 2021-09-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='pictures')),
                ('desc', models.TextField()),
                ('available', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=200)),
                ('document', models.FileField(null=True, upload_to='document')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.genre')),
            ],
        ),
    ]
